name: "Squash Docker Manifests"
description: "Squash multiple Docker tags into a single one, for multi-arch images"
inputs:
  source-tags:
    description: "List of source tags to squash"
    required: true
  destination-tag:
    description: "The single destination tag to squash into"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: "Squash input tags into a single tag, and push"
      run: squash.sh
      shell: bash
      env:
        INPUT_SOURCE_TAGS: ${{ inputs.source-tags }}
        INPUT_DESTINATION_TAG: ${{ inputs.destination-tag }}
